# ======================================================================
# ORGANIZATION SERVICE â€” PRODUCTION PROFILE
# ======================================================================

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:host.docker.internal}:${DB_PORT:5432}/${ORG_DB:organization_db}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  cloud:
    consul:
      host: ${CONSUL_HOST:consul}
      port: ${CONSUL_PORT:8500}
      discovery:
        prefer-ip-address: true
        ip-address: ${HOST_IP:organization-service}

cas:
  jwks-url: http://cas-server:9000/.well-known/jwks.json
  allowed-origins: ${CORS_ORIGIN_MEMO_UI:http://localhost:3001},${CORS_ORIGIN_ADMIN_UI:http://localhost:3002}

policy:
  engine:
    url: http://policy-engine-service:9001

logging:
  level:
    root: INFO
    com.enterprise.organization: INFO
    org.springframework.cloud: WARN
    com.cas.common: INFO

services:
  workflow-service:
    url: http://workflow-service:9002
  form-service:
    url: http://form-service:9006
  cas-server:
    url: http://cas-server:9000
  document-service:
    url: http://document-service:9010
  audit-service:
    url: http://audit-service:9009
    enabled: true